# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#about"
  weight = 10

[[main]]
  name = "Research"
  url = "#experience"
  weight = 20

[[main]]
  name = "Project"
  url = "#projects"
  weight = 30

[[main]]
  name = "Course"
  url = "#courses"
  weight = 40

[[main]]
  name = "Award"
  url = "#awards"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
[[main]]
  name = "CV"
  url = "media/CV_YaoYiran.pdf"
  weight = 70
